version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/mobile"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
