plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'dev.xikxp1.stereodrome'
version = '0.1.18'

android {
  namespace "expo.modules.stereodromecore"

  defaultConfig {
    minSdkVersion 26
    versionCode 1
    versionName "0.1.18"

    externalNativeBuild {
      cmake {
        arguments "-DANDROID_STL=c++_shared"
      }
    }
  }

  externalNativeBuild {
    cmake {
      path "src/main/cpp/CMakeLists.txt"
    }
  }
}
