import { defineConfig, lazyPlugins } from "vite-plus";
import { sveltekit } from "@sveltejs/kit/vite";
import tailwindcss from "@tailwindcss/vite";

const host = process.env["TAURI_DEV_HOST"];
const hasHost = typeof host === "string" && host.length > 0;

// https://vite.dev/config/
export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  test: {
    passWithNoTests: true,
  },
  lint: {
    plugins: ["oxc", "typescript", "unicorn", "react"],
    jsPlugins: [
      "eslint-plugin-svelte",
      {
        name: "vite-plus",
        specifier: "vite-plus/oxlint-plugin",
      },
    ],
    categories: {
      correctness: "warn",
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
    env: {
      builtin: true,
      browser: true,
      node: true,
    },
    ignorePatterns: [
      "build/",
      ".svelte-kit/",
      "dist/",
      "node_modules/",
      "target/",
      "src-tauri/target/",
      "mobile/",
      "mobile/node_modules/",
      "mobile/.expo/",
      "mobile/android/",
      "mobile/ios/",
    ],
    rules: {
      "accessor-pairs": "error",
      "array-callback-return": "error",
      "arrow-body-style": "off",
      "block-scoped-var": "error",
      "capitalized-comments": "off",
      "class-methods-use-this": "error",
      complexity: ["error", 50],
      "constructor-super": "error",
      curly: "off",
      "default-case": "off",
      "default-case-last": "error",
      "default-param-last": "error",
      eqeqeq: ["error", "always", { null: "ignore" }],
      "for-direction": "error",
      "func-name-matching": "error",
      "func-names": "off",
      "func-style": "off",
      "getter-return": "error",
      "grouped-accessor-pairs": "error",
      "guard-for-in": "error",
      "id-length": "off",
      "id-match": "error",
      "init-declarations": "off",
      "logical-assignment-operators": "error",
      "max-classes-per-file": "error",
      "max-depth": "error",
      "max-lines": [
        "error",
        { max: 1500, skipBlankLines: true, skipComments: true },
      ],
      "max-lines-per-function": [
        "error",
        {
          max: 300,
          skipBlankLines: true,
          skipComments: true,
          IIFEs: true,
        },
      ],
      "max-nested-callbacks": "error",
      "max-params": ["error", { max: 8 }],
      "max-statements": ["error", 100],
      "new-cap": "error",
      "no-alert": "error",
      "no-array-constructor": "error",
      "no-async-promise-executor": "error",
      "no-await-in-loop": "error",
      "no-bitwise": "error",
      "no-caller": "error",
      "no-case-declarations": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": "error",
      "no-console": "error",
      "no-const-assign": "error",
      "no-constant-binary-expression": "error",
      "no-constant-condition": "error",
      "no-constructor-return": "error",
      "no-continue": "off",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-div-regex": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-duplicate-imports": "error",
      "no-else-return": "error",
      "no-empty": "error",
      "no-empty-character-class": "error",
      "no-empty-function": "error",
      "no-empty-pattern": "error",
      "no-empty-static-block": "error",
      "no-eq-null": "off",
      "no-eval": "error",
      "no-ex-assign": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-boolean-cast": "error",
      "no-extra-label": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-global-assign": "error",
      "no-implicit-coercion": "off",
      "no-implicit-globals": "error",
      "no-implied-eval": "error",
      "no-import-assign": "error",
      "no-inline-comments": "off",
      "no-inner-declarations": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-iterator": "error",
      "no-label-var": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "off",
      "no-loop-func": "error",
      "no-loss-of-precision": "error",
      "no-magic-numbers": "off",
      "no-misleading-character-class": "error",
      "no-multi-assign": "error",
      "no-multi-str": "error",
      "no-negated-condition": "off",
      "no-nested-ternary": "off",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-native-nonconstructor": "error",
      "no-new-wrappers": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-obj-calls": "error",
      "no-object-constructor": "error",
      "no-param-reassign": "error",
      "no-plusplus": "off",
      "no-promise-executor-return": "error",
      "no-proto": "error",
      "no-prototype-builtins": "error",
      "no-redeclare": "error",
      "no-regex-spaces": "error",
      "no-restricted-exports": "error",
      "no-restricted-globals": "error",
      "no-restricted-imports": "error",
      "no-restricted-properties": "error",
      "no-return-assign": "error",
      "no-script-url": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-setter-return": "error",
      "no-shadow": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-template-curly-in-string": "error",
      "no-ternary": "off",
      "no-this-before-super": "error",
      "no-throw-literal": "error",
      "no-unassigned-vars": "error",
      "no-undef": "error",
      "no-undefined": "off",
      "no-underscore-dangle": "error",
      "no-unexpected-multiline": "error",
      "no-unmodified-loop-condition": "error",
      "no-unneeded-ternary": "error",
      "no-unreachable": "error",
      "no-unreachable-loop": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-expressions": "error",
      "no-unused-labels": "error",
      "no-unused-private-class-members": "error",
      "no-unused-vars": "error",
      "no-use-before-define": "off",
      "no-useless-assignment": "error",
      "no-useless-backreference": "error",
      "no-useless-call": "error",
      "no-useless-catch": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-constructor": "error",
      "no-useless-escape": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "no-void": ["error", { allowAsStatement: true }],
      "no-warning-comments": "error",
      "no-with": "error",
      "object-shorthand": "error",
      "operator-assignment": "error",
      "prefer-arrow-callback": "off",
      "prefer-const": "error",
      "prefer-destructuring": "off",
      "prefer-exponentiation-operator": "error",
      "prefer-named-capture-group": "off",
      "prefer-numeric-literals": "error",
      "prefer-object-has-own": "error",
      "prefer-object-spread": "error",
      "prefer-promise-reject-errors": "error",
      "prefer-regex-literals": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      "preserve-caught-error": "error",
      radix: "error",
      "require-await": "error",
      "require-unicode-regexp": "off",
      "require-yield": "error",
      "sort-keys": "off",
      "sort-vars": "error",
      "symbol-description": "error",
      "unicode-bom": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "vars-on-top": "error",
      yoda: "error",
      "svelte/block-lang": [
        "error",
        {
          script: "ts",
          style: null,
        },
      ],
      "svelte/button-has-type": "error",
      "svelte/comment-directive": "error",
      "svelte/derived-has-same-inputs-outputs": "error",
      "svelte/experimental-require-slot-types": "error",
      "svelte/experimental-require-strict-events": "error",
      "svelte/infinite-reactive-loop": "error",
      "svelte/max-lines-per-block": "error",
      "svelte/no-add-event-listener": "error",
      "svelte/no-at-const-tags": "error",
      "svelte/no-at-debug-tags": "error",
      "svelte/no-at-html-tags": "error",
      "svelte/no-dom-manipulating": "error",
      "svelte/no-dupe-else-if-blocks": "error",
      "svelte/no-dupe-on-directives": "error",
      "svelte/no-dupe-style-properties": "error",
      "svelte/no-dupe-use-directives": "error",
      "svelte/no-export-load-in-svelte-module-in-kit-pages": "error",
      "svelte/no-extra-reactive-curlies": "error",
      "svelte/no-ignored-unsubscribe": "error",
      "svelte/no-immutable-reactive-statements": "error",
      "svelte/no-inner-declarations": "error",
      "svelte/no-inspect": "error",
      "svelte/no-navigation-without-resolve": "error",
      "svelte/no-nested-style-tag": "error",
      "svelte/no-not-function-handler": "error",
      "svelte/no-object-in-text-mustaches": "error",
      "svelte/no-raw-special-elements": "error",
      "svelte/no-reactive-functions": "error",
      "svelte/no-reactive-literals": "error",
      "svelte/no-reactive-reassign": "error",
      "svelte/no-shorthand-style-property-overrides": "error",
      "svelte/no-store-async": "error",
      "svelte/no-svelte-internal": "error",
      "svelte/no-target-blank": "error",
      "svelte/no-top-level-browser-globals": "error",
      "svelte/no-unknown-style-directive-property": "error",
      "svelte/no-unnecessary-state-wrap": "error",
      "svelte/no-unused-props": "error",
      "svelte/no-unused-svelte-ignore": "error",
      "svelte/no-useless-children-snippet": "error",
      "svelte/no-useless-mustaches": "error",
      "svelte/prefer-const": "off",
      "svelte/prefer-derived-over-derived-by": "error",
      "svelte/prefer-destructured-store-props": "error",
      "svelte/prefer-svelte-reactivity": "error",
      "svelte/prefer-writable-derived": "error",
      "svelte/require-each-key": "error",
      "svelte/require-event-dispatcher-types": "error",
      "svelte/require-event-prefix": "error",
      "svelte/require-optimized-style-attribute": "error",
      "svelte/require-store-callbacks-use-set-param": "error",
      "svelte/require-store-reactive-access": "error",
      "svelte/require-stores-init": "error",
      "svelte/spaced-html-comment": "error",
      "svelte/system": "error",
      "svelte/valid-compile": "error",
      "svelte/valid-each-key": "error",
      "svelte/valid-prop-names-in-kit-pages": "error",
      "svelte/valid-style-parse": "error",
      "typescript/consistent-return": "error",
      "typescript/dot-notation": "error",
      "unicorn/no-new-array": "off",
      "vite-plus/prefer-vite-plus-imports": "error",
    },
    overrides: [
      {
        files: ["src/**/*.ts", "vite.config.ts"],
        rules: {
          "constructor-super": "off",
          "getter-return": "off",
          "no-class-assign": "off",
          "no-const-assign": "off",
          "no-dupe-keys": "off",
          "no-func-assign": "off",
          "no-import-assign": "off",
          "no-new-native-nonconstructor": "off",
          "no-obj-calls": "off",
          "no-setter-return": "off",
          "no-this-before-super": "off",
          "no-undef": "off",
          "no-unreachable": "off",
          "no-unsafe-negation": "off",
          "no-with": "off",
          "no-implied-eval": "off",
          "no-unused-private-class-members": "off",
          "no-throw-literal": "off",
          "prefer-destructuring": "off",
          "prefer-promise-reject-errors": "off",
          "require-await": "off",
          "typescript/adjacent-overload-signatures": "error",
          "typescript/array-type": "error",
          "typescript/await-thenable": "error",
          "typescript/ban-ts-comment": "error",
          "typescript/ban-tslint-comment": "error",
          "typescript/class-literal-property-style": "error",
          "typescript/consistent-generic-constructors": "error",
          "typescript/consistent-indexed-object-style": "error",
          "typescript/consistent-return": "off",
          "typescript/consistent-type-assertions": "error",
          "typescript/consistent-type-definitions": "error",
          "typescript/consistent-type-exports": "error",
          "typescript/consistent-type-imports": "error",
          "typescript/dot-notation": "off",
          "typescript/explicit-function-return-type": "error",
          "typescript/explicit-member-accessibility": "error",
          "typescript/explicit-module-boundary-types": "error",
          "typescript/method-signature-style": "error",
          "typescript/no-array-delete": "error",
          "typescript/no-base-to-string": "error",
          "typescript/no-confusing-non-null-assertion": "error",
          "typescript/no-confusing-void-expression": "error",
          "typescript/no-deprecated": "error",
          "typescript/no-duplicate-enum-values": "error",
          "typescript/no-duplicate-type-constituents": "error",
          "typescript/no-dynamic-delete": "error",
          "typescript/no-empty-object-type": "error",
          "typescript/no-explicit-any": "error",
          "typescript/no-extra-non-null-assertion": "error",
          "typescript/no-extraneous-class": "error",
          "typescript/no-floating-promises": "error",
          "typescript/no-for-in-array": "error",
          "typescript/no-implied-eval": "error",
          "typescript/no-import-type-side-effects": "error",
          "typescript/no-inferrable-types": "error",
          "typescript/no-invalid-void-type": "error",
          "typescript/no-meaningless-void-operator": "error",
          "typescript/no-misused-new": "error",
          "typescript/no-misused-promises": "error",
          "typescript/no-misused-spread": "error",
          "typescript/no-mixed-enums": "error",
          "typescript/no-namespace": "error",
          "typescript/no-non-null-asserted-nullish-coalescing": "error",
          "typescript/no-non-null-asserted-optional-chain": "error",
          "typescript/no-non-null-assertion": "error",
          "typescript/no-redundant-type-constituents": "error",
          "typescript/no-require-imports": "error",
          "typescript/no-restricted-types": "error",
          "typescript/no-this-alias": "error",
          "typescript/no-unnecessary-boolean-literal-compare": "error",
          "typescript/no-unnecessary-condition": "error",
          "typescript/no-unnecessary-parameter-property-assignment": "error",
          "typescript/no-unnecessary-qualifier": "error",
          "typescript/no-unnecessary-template-expression": "error",
          "typescript/no-unnecessary-type-arguments": "error",
          "typescript/no-unnecessary-type-assertion": "error",
          "typescript/no-unnecessary-type-constraint": "error",
          "typescript/no-unnecessary-type-conversion": "error",
          "typescript/no-unnecessary-type-parameters": "error",
          "typescript/no-unsafe-argument": "error",
          "typescript/no-unsafe-assignment": "error",
          "typescript/no-unsafe-call": "error",
          "typescript/no-unsafe-declaration-merging": "error",
          "typescript/no-unsafe-enum-comparison": "error",
          "typescript/no-unsafe-function-type": "error",
          "typescript/no-unsafe-member-access": "error",
          "typescript/no-unsafe-return": "error",
          "typescript/no-unsafe-type-assertion": "error",
          "typescript/no-unsafe-unary-minus": "error",
          "typescript/no-useless-default-assignment": "error",
          "typescript/no-useless-empty-export": "error",
          "typescript/no-wrapper-object-types": "error",
          "typescript/non-nullable-type-assertion-style": "error",
          "typescript/only-throw-error": "error",
          "typescript/parameter-properties": "error",
          "typescript/prefer-as-const": "error",
          "typescript/prefer-enum-initializers": "error",
          "typescript/prefer-find": "error",
          "typescript/prefer-for-of": "error",
          "typescript/prefer-function-type": "error",
          "typescript/prefer-includes": "error",
          "typescript/prefer-literal-enum-member": "error",
          "typescript/prefer-namespace-keyword": "error",
          "typescript/prefer-nullish-coalescing": "error",
          "typescript/prefer-optional-chain": "error",
          "typescript/prefer-promise-reject-errors": "error",
          "typescript/prefer-readonly": "error",
          "typescript/prefer-readonly-parameter-types": "error",
          "typescript/prefer-reduce-type-parameter": "error",
          "typescript/prefer-regexp-exec": "error",
          "typescript/prefer-return-this-type": "error",
          "typescript/prefer-string-starts-ends-with": "error",
          "typescript/promise-function-async": "error",
          "typescript/related-getter-setter-pairs": "error",
          "typescript/require-array-sort-compare": "error",
          "typescript/require-await": "error",
          "typescript/restrict-plus-operands": "error",
          "typescript/restrict-template-expressions": "error",
          "typescript/return-await": "error",
          "typescript/strict-boolean-expressions": "error",
          "typescript/strict-void-return": "error",
          "typescript/switch-exhaustiveness-check": "error",
          "typescript/triple-slash-reference": "error",
          "typescript/unbound-method": "error",
          "typescript/unified-signatures": "error",
          "typescript/use-unknown-in-catch-callback-variable": "error",
        },
      },
      {
        files: ["*.svelte", "**/*.svelte"],
        rules: {
          curly: "off",
          "no-inner-declarations": "off",
          "no-self-assign": "off",
          "no-undef": "off",
        },
        jsPlugins: ["eslint-plugin-svelte"],
      },
      {
        files: ["**/*.svelte"],
        rules: {
          "no-unused-vars": "off",
          "prefer-const": "off",
          "svelte/prefer-destructured-store-props": "off",
        },
      },
      {
        files: ["src/**/*.ts", "vite.config.ts"],
        rules: {
          "class-methods-use-this": "off",
          "no-magic-numbers": "off",
          "no-use-before-define": "off",
          "max-params": [
            "error",
            {
              max: 8,
            },
          ],
          "typescript/consistent-type-definitions": "off",
          "typescript/explicit-function-return-type": "off",
          "typescript/explicit-module-boundary-types": "off",
          "typescript/explicit-member-accessibility": "off",
          "typescript/dot-notation": "off",
          "typescript/method-signature-style": "off",
          "typescript/no-inferrable-types": "off",
          "typescript/prefer-readonly-parameter-types": "off",
          "typescript/promise-function-async": "off",
          "typescript/restrict-template-expressions": [
            "error",
            {
              allowBoolean: true,
              allowNullish: true,
              allowNumber: true,
            },
          ],
          "typescript/switch-exhaustiveness-check": "error",
          "typescript/unbound-method": [
            "error",
            {
              ignoreStatic: true,
            },
          ],
        },
      },
      {
        files: ["scripts/set-version.mjs"],
        rules: {
          "no-console": "off",
        },
      },
    ],
  },
  fmt: {
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "es5",
    printWidth: 80,
    sortPackageJson: false,
    svelte: {},
    ignorePatterns: [
      "build/",
      ".svelte-kit/",
      "dist/",
      "node_modules/",
      "src-tauri/target/",
      "target/",
      "src-tauri/gen/",
      "mobile/.expo/",
      "mobile/android/",
      "mobile/ios/",
      ".serena/",
      "bun.lockb",
      "src-tauri/bundle/linux/main.desktop.hbs",
    ],
  },
  // oxlint-disable-next-line typescript/no-non-null-assertion -- lazyPlugins is defined for this static plugin factory.
  plugins: lazyPlugins(() => [sveltekit(), tailwindcss()])!,

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent Vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: 1420,
    strictPort: true,
    host: hasHost ? host : false,
    ...(hasHost
      ? {
          hmr: {
            protocol: "ws",
            host,
            port: 1421,
          },
        }
      : {}),
    watch: {
      // 3. tell Vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**"],
    },
  },
});
