[package]
name = "stereodrome-audio"
version = "0.1.19"
edition = "2024"
publish = false

[dependencies]
bs2b = { version = "0.2.0", features = ["streaming"] }
ebur128 = "0.1.10"
fundsp = "0.23.0"
log = "0.4.29"
ringbuf = "0.4.8"
rodio = { version = "0.22.2", features = ["symphonia-all"] }
rustfft = "6.4.1"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
