[package]
name = "stereodrome-audio"
version = "0.3.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
bs2b = { version = "0.2.2", features = ["streaming"] }
ebur128 = "0.1.10"
fundsp = "0.23.0"
log = "0.4.33"
ringbuf = "0.5.1"
rodio = { version = "0.22.2", features = ["symphonia-all"] }
rustfft = "6.4.1"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
