/* eslint-disable */
// @generated by `scripts/generate-protocol-types.sh`.
// Source of truth: crates/stereodrome-core/src/{models,queue,lastfm,backup,protocol}.rs
// Do not hand-edit.

export const CORE_PROTOCOL_VERSION = 1 as const;

export type ConnectParams = { url: string; username: string; password: string };

export type ServerSettingsUpdate = { url?: string; username?: string };

export type ConnectionStatus = {
  connected: boolean;
  server_url: string | null;
  username: string | null;
  server_version: string | null;
};

export type Artist = {
  id: string;
  name: string;
  album_count: number;
  cover_art_id: string | null;
  synced_at: string;
};

export type Album = {
  id: string;
  artist_id: string;
  name: string;
  year: number | null;
  song_count: number;
  duration: number | null;
  cover_art_id: string | null;
  synced_at: string;
  artist_name: string | null;
};

export type AlbumListEntry = {
  id: string;
  name: string;
  artist_id: string | null;
  artist_name: string | null;
  year: number | null;
  song_count: number | null;
  duration: number | null;
  cover_art_id: string | null;
  play_count: number | null;
  created: string | null;
};

export type Song = {
  id: string;
  album_id: string;
  artist_id: string;
  title: string;
  track_number: number | null;
  disc_number: number;
  duration: number | null;
  bit_rate: number | null;
  size: number | null;
  suffix: string | null;
  content_type: string | null;
  path: string | null;
  year: number | null;
  genre: string | null;
  synced_at: string;
  artist: string | null;
  album: string | null;
};

export type Playlist = {
  id: string;
  name: string;
  song_count: number;
  duration: number;
  owner: string | null;
  cover_art_id: string | null;
  created_at: string;
  changed_at: string;
  saved_offline: boolean;
  offline_saved_at: string | null;
};

export type SearchResultSong = {
  id: string;
  title: string;
  artist: string | null;
  album: string | null;
  duration: number | null;
};

export type SearchResultAlbum = {
  id: string;
  name: string;
  artist: string | null;
  year: number | null;
  song_count: number;
};

export type SearchResultArtist = {
  id: string;
  name: string;
  album_count: number;
};

export type SearchResults = {
  songs: Array<SearchResultSong>;
  albums: Array<SearchResultAlbum>;
  artists: Array<SearchResultArtist>;
};

export type SyncResult = { artists: number; albums: number; songs: number };

export type SyncSettings = {
  incremental_enabled: boolean;
  incremental_interval_minutes: number;
  full_reconcile_enabled: boolean;
  full_reconcile_interval_hours: number;
};

export type SyncJobStatus = {
  enabled: boolean;
  interval_minutes: number;
  running: boolean;
  last_attempt_at: string | null;
  last_success_at: string | null;
  last_error: string | null;
  next_run_at: string | null;
};

export type LibrarySyncStatus = {
  active_job: string | null;
  full: SyncJobStatus;
  incremental: SyncJobStatus;
  full_reconcile: SyncJobStatus;
};

export type ConnectivitySettings = { manual_offline_enabled: boolean };

export type ScanStatus = { scanning: boolean; count: number | null };

export type NowPlayingEntry = {
  id: string;
  title: string;
  artist: string | null;
  album: string | null;
  duration: number | null;
  cover_art: string | null;
  username: string;
  minutes_ago: number;
  player_name: string | null;
};

export type CacheStats = {
  total_size: number;
  file_count: number;
  max_size: number;
};

export type DownloadStatus = {
  song_id: string;
  cached: boolean;
  path: string | null;
  bytes: number;
};

export type SavedPlaylistOfflineResult = {
  playlist_id: string;
  saved_offline: boolean;
  downloaded_count: number;
  removed_count: number;
  skipped_protected_count: number;
};

export type PlaybackState = {
  current_song_id: string | null;
  position_seconds: number;
  duration_seconds: number;
  was_playing: boolean;
  app_volume: number;
  updated_at: string;
};

export type PlaybackProgress = {
  song_id: string;
  position_seconds: number;
  duration_seconds: number;
  is_playing: boolean;
};

export type AudioProcessingSettings = {
  normalization_enabled: boolean;
  normalization_mode: string;
  target_lufs: number;
  preamp_db: number;
  prevent_clipping: boolean;
  dynamics_enabled: boolean;
  dynamics_preset: string;
  binaural_enabled: boolean;
  binaural_preset: string;
  equalizer_enabled: boolean;
  equalizer_bands_db: Array<number>;
  gapless_enabled: boolean;
  crossfade_enabled: boolean;
  crossfade_duration_ms: number;
  prefetch_count: number;
};

export type BackupSummary = {
  artists: number;
  albums: number;
  songs: number;
  playlists: number;
  queue_items: number;
};

export type LastfmStatus = {
  available: boolean;
  authenticated: boolean;
  enabled: boolean;
  username: string | null;
  pending_auth: boolean;
  queue_count: number;
  last_error: string | null;
};

export type LastfmAuthStart = { auth_url: string };

export type LastfmQueueItem = {
  id: number;
  song_id: string;
  title: string;
  artist: string;
  album: string | null;
  duration: number | null;
  played_at: number;
  attempts: number;
  next_retry_at: number;
  last_error: string | null;
  created_at: string;
  updated_at: string;
};

export type RepeatMode = "Off" | "All" | "One";

export type QueueItem = {
  song_id: string;
  title: string;
  artist: string;
  album: string;
  duration: number;
};

export type QueueState = {
  items: Array<QueueItem>;
  current_index: number | null;
  shuffle: boolean;
  repeat_mode: RepeatMode;
  pending_navigation_index: number | null;
  prepared_next_item: QueueItem | null;
};

export type CommandId = number;

export type OperationId = number;

export type SyncKind = "full" | "incremental" | "full-reconcile";

export type PlatformLifecycle = "foreground" | "background";

export type JobKind =
  | "connect"
  | "restore-session"
  | { sync: { kind: SyncKind } }
  | "background-tick"
  | { "download-song": { song_id: string } }
  | { "download-album": { album_id: string } }
  | { "download-playlist": { playlist_id: string } }
  | "saved-playlist-reconcile"
  | "queue-prefetch"
  | { "playback-prepare": { song_id: string } }
  | "server-request";

export type PlaybackNavigation =
  | { type: "index"; index: number }
  | { type: "next"; force: boolean }
  | { type: "previous" };

export type PlatformPlaybackEvent =
  | { type: "interruption-began" }
  | { type: "interruption-ended"; should_resume: boolean }
  | { type: "audio-focus-lost"; transient: boolean }
  | { type: "audio-focus-gained" }
  | { type: "route-lost" }
  | { type: "media-services-reset" };

export type OperationPhase = "running" | "cancelling";

export type OperationSnapshot = {
  operation_id: OperationId;
  cause_command_id: CommandId;
  kind: JobKind;
  phase: OperationPhase;
};

export type SavedPlaylistOfflineStatus = {
  running: boolean;
  operation_id: OperationId | null;
  last_error: string | null;
};

export type RuntimeLifecycle =
  | "starting"
  | "ready"
  | "shutting-down"
  | "faulted";

export type ConnectivityState =
  | { status: "unconfigured" }
  | {
      status: "offline-manual";
      server_url: string | null;
      username: string | null;
    }
  | { status: "disconnected"; server_url: string; username: string }
  | {
      status: "online";
      server_url: string;
      username: string;
      server_version: string | null;
    };

export type DownloadSnapshot = {
  downloading_song_ids: Array<string>;
  offline_song_ids: Array<string>;
};

export type PlaybackProjectionSong = {
  id: string;
  title: string;
  artist: string;
  album: string;
  duration_seconds: number;
  artwork_uri: string | null;
};

export type PlaybackPhase = "playing" | "paused" | "stopped" | "stalled";

export type PlaybackOutputState = "closed" | "ready" | "failed" | "unavailable";

export type PlaybackProjection = {
  state: PlaybackPhase;
  is_playing: boolean;
  audio_loaded: boolean;
  output_state: PlaybackOutputState;
  song: PlaybackProjectionSong | null;
  position_seconds: number;
  duration_seconds: number;
  volume: number;
  queue: QueueState;
  queue_index: number | null;
  queue_length: number;
  can_play: boolean;
  can_next: boolean;
  can_previous: boolean;
  can_seek: boolean;
  preparing_operation_id: OperationId | null;
};

export type CoreSnapshot = {
  protocol_version: number;
  revision: number;
  lifecycle: RuntimeLifecycle;
  connectivity: ConnectivityState;
  playback: PlaybackProjection;
  queue: QueueState;
  sync: LibrarySyncStatus;
  downloads: DownloadSnapshot;
  operations: Array<OperationSnapshot>;
  saved_playlist_offline: SavedPlaylistOfflineStatus;
  platform_lifecycle: PlatformLifecycle;
  network_available: boolean;
  settings_revision: number;
  library_revision: number;
  last_failure: OperationFailure | null;
};

export type ProtocolErrorCode =
  | "unsupported_protocol_version"
  | "invalid_command_id"
  | "invalid_input"
  | "not_connected"
  | "offline_mode"
  | "conflict"
  | "runtime_unavailable"
  | "cancelled"
  | "persistence"
  | "network"
  | "audio"
  | "internal";

export type ProtocolError = {
  code: ProtocolErrorCode;
  message: string;
  retryable: boolean;
};

export type OperationFailure = {
  command_id: CommandId;
  operation_id: OperationId | null;
  error: ProtocolError;
};

export type CommandStatus = "succeeded" | "failed";

export type CoreCommand =
  | { type: "initialize" }
  | { type: "get-snapshot" }
  | { type: "connect"; params: ConnectParams }
  | { type: "update-server-settings"; update: ServerSettingsUpdate }
  | { type: "restore-session" }
  | { type: "disconnect" }
  | { type: "get-connection-status" }
  | { type: "get-sync-settings" }
  | { type: "set-sync-settings"; settings: SyncSettings }
  | { type: "get-connectivity-settings" }
  | { type: "set-connectivity"; settings: ConnectivitySettings }
  | { type: "report-network"; available: boolean }
  | { type: "report-lifecycle"; lifecycle: PlatformLifecycle }
  | { type: "start-sync"; kind: SyncKind }
  | { type: "run-background-tick" }
  | { type: "cancel-operation"; operation_id: OperationId }
  | { type: "run-due-library-sync" }
  | { type: "get-scan-status" }
  | { type: "start-scan" }
  | { type: "get-now-playing" }
  | { type: "get-library-sync-status" }
  | { type: "get-artists" }
  | { type: "get-albums"; artist_id: string | null }
  | { type: "get-songs"; album_id: string | null; artist_id: string | null }
  | {
      type: "get-album-list";
      list_type: string;
      size: number | null;
      offset: number | null;
    }
  | { type: "search-library"; query: string; limit: number | null }
  | { type: "get-playlists" }
  | { type: "get-playlist-songs"; playlist_id: string }
  | { type: "create-playlist"; name: string; song_ids: Array<string> }
  | { type: "rename-playlist"; playlist_id: string; name: string }
  | { type: "delete-playlist"; playlist_id: string }
  | {
      type: "add-songs-to-playlist";
      playlist_id: string;
      song_ids: Array<string>;
    }
  | {
      type: "remove-songs-from-playlist";
      playlist_id: string;
      song_indexes: Array<number>;
    }
  | { type: "get-cover-art-uri"; id: string; size: number | null }
  | { type: "get-song-cover-art-uri"; id: string; size: number | null }
  | { type: "get-stream-uri"; song_id: string }
  | { type: "get-audio-cache-stats" }
  | { type: "get-offline-song-ids" }
  | { type: "set-max-cache-size"; max_size: number }
  | { type: "clear-audio-cache" }
  | { type: "is-song-cached"; song_id: string }
  | { type: "download-song"; song_id: string }
  | { type: "remove-cached-song"; song_id: string }
  | { type: "download-album"; album_id: string }
  | { type: "download-playlist"; playlist_id: string }
  | {
      type: "set-playlist-saved-offline";
      playlist_id: string;
      saved_offline: boolean;
    }
  | { type: "reconcile-saved-playlists-offline" }
  | { type: "start-saved-playlists-offline-reconcile" }
  | { type: "get-saved-playlists-offline-status" }
  | { type: "start-queue-prefetch"; reserve_first?: boolean }
  | { type: "cancel-queue-prefetch"; invalidate_completed?: boolean }
  | { type: "get-playback-state" }
  | { type: "save-playback-position"; progress: PlaybackProgress }
  | { type: "get-lastfm-status" }
  | { type: "begin-lastfm-auth" }
  | { type: "complete-lastfm-auth" }
  | { type: "disconnect-lastfm" }
  | { type: "get-lastfm-queue" }
  | { type: "retry-lastfm-queue" }
  | { type: "get-audio-processing-settings" }
  | { type: "set-audio-processing"; settings: AudioProcessingSettings }
  | { type: "export-portable-backup"; path: string }
  | { type: "import-portable-backup"; path: string }
  | { type: "get-queue" }
  | { type: "play-selection"; song_id: string; song_ids: Array<string> }
  | { type: "clear-playback" }
  | { type: "navigate-playback"; navigation: PlaybackNavigation }
  | { type: "toggle-playback" }
  | { type: "pause-playback" }
  | { type: "resume-playback" }
  | { type: "stop-playback" }
  | { type: "seek-to"; seconds: number }
  | { type: "seek-by"; seconds: number }
  | { type: "set-playback-volume"; volume: number }
  | { type: "rebuild-audio-output" }
  | { type: "apply-audio-settings" }
  | { type: "prepare-next-transition" }
  | { type: "report-platform-playback"; event: PlatformPlaybackEvent }
  | { type: "add-to-queue"; item: QueueItem }
  | { type: "add-songs-to-queue"; items: Array<QueueItem> }
  | { type: "insert-next"; item: QueueItem }
  | { type: "insert-next-songs"; items: Array<QueueItem> }
  | { type: "remove-from-queue"; index: number }
  | { type: "clear-queue" }
  | { type: "move-queue-item"; from: number; to: number }
  | { type: "play-queue-item"; index: number }
  | { type: "play-next"; force: boolean | null }
  | { type: "play-previous" }
  | { type: "toggle-shuffle" }
  | { type: "set-repeat-mode"; mode: RepeatMode }
  | { type: "cycle-repeat-mode" }
  | { type: "reroll-next" }
  | { type: "shutdown" };

export type CoreCommandRequest = {
  protocol_version: number;
  command_id: CommandId;
  command: CoreCommand;
};

export type CoreCommandResult = {
  protocol_version: number;
  command_id: CommandId;
  accepted_revision: number;
  operation_id: OperationId | null;
  status: CommandStatus;
  value: JsonValue | null;
  error: ProtocolError | null;
};

export type CoreEventKind =
  | { type: "snapshot-changed"; snapshot: CoreSnapshot }
  | { type: "operation-failed"; failure: OperationFailure }
  | { type: "runtime-shutting-down" };

export type CoreEvent = {
  protocol_version: number;
  stream_id: number;
  event_id: number;
  revision: number;
  cause_command_id: CommandId;
  operation_id: OperationId | null;
  kind: CoreEventKind;
};

export type JsonValue =
  | number
  | string
  | boolean
  | Array<JsonValue>
  | { [key in string]: JsonValue }
  | null;

export type CoreCommandValue = {
  connect: ConnectionStatus;
  "update-server-settings": ConnectionStatus;
  "restore-session": ConnectionStatus;
  "get-connection-status": ConnectionStatus;
  "get-sync-settings": SyncSettings;
  "set-sync-settings": SyncSettings;
  "get-connectivity-settings": ConnectivitySettings;
  "set-connectivity": ConnectivitySettings;
  "run-due-library-sync": string | null;
  "get-scan-status": ScanStatus;
  "start-scan": ScanStatus;
  "get-now-playing": Array<NowPlayingEntry>;
  "get-library-sync-status": LibrarySyncStatus;
  "get-artists": Array<Artist>;
  "get-albums": Array<Album>;
  "get-songs": Array<Song>;
  "get-album-list": Array<AlbumListEntry>;
  "search-library": SearchResults;
  "get-playlists": Array<Playlist>;
  "get-playlist-songs": Array<Song>;
  "create-playlist": Playlist;
  "get-cover-art-uri": string;
  "get-song-cover-art-uri": string | null;
  "get-stream-uri": string;
  "get-audio-cache-stats": CacheStats;
  "get-offline-song-ids": Array<string>;
  "set-max-cache-size": CacheStats;
  "clear-audio-cache": CacheStats;
  "is-song-cached": DownloadStatus;
  "download-song": DownloadStatus;
  "remove-cached-song": DownloadStatus;
  "download-album": Array<DownloadStatus>;
  "download-playlist": Array<DownloadStatus>;
  "set-playlist-saved-offline": SavedPlaylistOfflineResult;
  "reconcile-saved-playlists-offline": Array<SavedPlaylistOfflineResult>;
  "start-saved-playlists-offline-reconcile": Array<SavedPlaylistOfflineResult>;
  "get-saved-playlists-offline-status": SavedPlaylistOfflineStatus;
  "start-queue-prefetch": Array<DownloadStatus>;
  "get-playback-state": PlaybackState;
  "save-playback-position": PlaybackState;
  "get-lastfm-status": LastfmStatus;
  "begin-lastfm-auth": LastfmAuthStart;
  "complete-lastfm-auth": LastfmStatus;
  "disconnect-lastfm": LastfmStatus;
  "get-lastfm-queue": Array<LastfmQueueItem>;
  "retry-lastfm-queue": number;
  "get-audio-processing-settings": AudioProcessingSettings;
  "set-audio-processing": AudioProcessingSettings;
  "export-portable-backup": BackupSummary;
  "import-portable-backup": BackupSummary;
  "get-queue": QueueState;
  "clear-playback": QueueState;
  "navigate-playback": QueueState;
  "add-to-queue": QueueState;
  "add-songs-to-queue": QueueState;
  "insert-next": QueueState;
  "insert-next-songs": QueueState;
  "remove-from-queue": QueueState;
  "clear-queue": QueueState;
  "move-queue-item": QueueState;
  "toggle-shuffle": QueueState;
  "set-repeat-mode": QueueState;
  "cycle-repeat-mode": QueueState;
  "reroll-next": QueueState;
  "play-queue-item": QueueItem | null;
  "play-next": QueueItem | null;
  "play-previous": QueueItem | null;
};
